version: "2"

services: 
    app:
        container_name: app
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - '.:/app'
        ports:
            - '8080:8080'